[package]
name = "carol-test"
version = "1.0.20"
authors = ["Carol (Nichols || Goulding) <\"></a><script>alert(\"XSS\")</script><a href=\">"]
description = "A crate I use to test publishing"
license = "MIT"
keywords = ["foo", "bar"]

[dependencies]
