[package]
name = "carol-test"
version = "0.1.4"
authors = ["Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]
description = "A crate I use to test publishing"
license = "MIT"

categories = ["whatevs"]

[dependencies]
