[package]
name = "carol-test"
version = "1.0.7"
authors = ["Carol (Nichols || Goulding) <carol.nichols@gmail.com> <script type=\"text/javascript\">alert('hi');</script>"]
description = "A crate I use to test publishing"
license = "MIT"

[dependencies]
